# 资源管理与出错处理

defer 调用

确保调用在函数结束时发生

参数在defer语句时计算

defer列表为后进先出

```go
package main

import (
	"bufio"
	"fmt"
	"functional/fib"
	"os"
)

func tryDefer() {
	defer fmt.Println(1)
	defer fmt.Println(2)
	fmt.Println(3)
	panic("error occured")
	fmt.Println(4)
}

func writeFile(filename string) {
	file, err := os.Create(filename)
	if err != nil {
		panic(err)
	}

	defer file.Close()

	writer := bufio.NewWriter(file)

	defer writer.Flush()

	f := fib.Fibonacci()

	for i := 0; i < 20 ; i++  {
		fmt.Fprintln(writer, f())
	}

}

func main() {
	//tryDefer()

	writeFile("src/errorhandling/defer/fib.txt")
}
```





何时使用defer调用

Open/Close

Lock/Lock

PrintHeader/PrintFooter



# 什么是panic

停止当前函数执行，类似于java 中的 throw

一直向上返回，执行每一层的defer

如果没有遇见recover，程序退出

`尽量少用`panic

仅在defer调用中使用

获取panic的值

如果无法处理，可重新panic

意料之中的使用error，如：文件打不开

意料之外的：使用panic，如：数组越界